repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: trailing-whitespace
        exclude: .bumpversion.cfg

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        files: '^docs/.*\.md$'
        additional_dependencies:
          - mdformat-gfm
          - mdformat-myst

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
      - id: check-manifest
        args: [ --no-build-isolation ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
      - id: pyupgrade
        args: [ --py36-plus, --keep-runtime-typing ]
        description: Automatically upgrade syntax for newer versions of the python language.

  - repo: https://github.com/peterdemin/pip-compile-multi
    rev: v2.4.6
    hooks:
      - id: pip-compile-multi-verify

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-typing-imports ]
