# Read the Docs configuration file (v2)
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      # TODO: This is a workaround due to a bug in kaleido/scopes/plotly.py#L64
      #       where `which_browser()` returns None.
      - BROWSER_PATH='None'

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
