[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "pytest {project}/tests/unit/test_missing.py --no-cov"

[tool.black]
line-length = 100
include = '\.pyi?$'
