# ================================================
# Top-level settings
# ================================================
target-version = "py38"
fix = true
line-length = 100

# ================================================
# Formatting settings (currently not used)
# ================================================
[format]
line-ending = "lf"
docstring-code-format = true

# ================================================
# Linting settings
# ================================================
[lint]
select = ["ALL"]
ignore = [
    # Ignored groups:
    "FBT", # flake8-boolean-trap

    # flake8-comprehensions
    "C408", # Unnecessary `dict` call (rewrite as a literal)

    # pydocstyle
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D205", # 1 blank line required between summary line and description
    "D209", # Multi-line docstring closing quotes should be on a separate line
    "D400", # First line should end with a period
    "D415", # First line should end with a period, question mark, or exclamation point

    # pylint
    "PLR0913", # Too many arguments to function call ({x} > 5)
    "PLR2004", # Magic value used in comparison, consider replacing {x} with a constant variable

    # tryceratops
    "TRY003", # Avoid specifying long messages outside the exception class

    # flake8-commas (COM)
    "COM812", # Trailing comma missing

    # flake8-errmsg (EM)
    "EM101", # Exception must not use a string literal, assign to variable first
    "EM102", # Exception must not use an f-string literal, assign to variable first
    "EM103", # Exception must not use a .format() string directly, assign to variable first

    # pep8-naming
    # (allow for sklearn's naming convention for uppercase `X`)
    "N803", # Argument name should be lowercase
    "N806", # Variable in function should be lowercase
]

[lint.per-file-ignores]
"bin/*" = [
    "T201", # `print` found
]
"extras/*" = [
    "T201", # `print` found
]
"docs/*" = [
    "ERA001", # Found commented-out code
    "S101", # Use of assert detected
    "T201", # `print` found
]
"tests/*" = [
    "S101", # Use of assert detected
    "SLF001", # Private member accessed: `_X`
]

[lint.flake8-annotations]
mypy-init-return = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-import-conventions]
extend-aliases = { "numpy.typing" = "npt", "plotly.graph_objects" = "go" }
banned-from = ["pandas", "numpy"]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
required-imports = ["from __future__ import annotations"]
known-first-party = ["ridgeplot", "_ridgeplot_examples", "extras"]

[lint.mccabe]
max-complexity = 8

[lint.pycodestyle]
max-doc-length = 100

[lint.pydocstyle]
convention = "numpy"
