---
name: "Bug report"
description: "Report an issue you encountered with ridgeplot"
title: "[BUG] "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for your interest in improving ridgeplot!** 🚀

        We really appreciate you taking the time to help make this project better for everyone.

        We organize issues into three main categories:
        - ⭐ **Feature request**: Have an idea for a new feature or an enhancement to existing functionality? This is the place to share it.
        - 🐛 **Bug report**: Encountered a problem or noticed something not working as expected? Please let us know.
        - 📚 **Documentation improvement**: Spotted a typo, missing info, or have suggestions for a new section or example? We'd love to hear about it.

        Looks like you're about to submit a bug report.
        Please use the template below and provide as much detail as you can.
        The more information you provide, the easier it will be for us to understand and reproduce the issue you encountered.

        For broader discussions, questions, or general feedback, please head over to [GitHub Discussions](https://github.com/tpvasconcelos/ridgeplot/discussions).

        Our response times may vary, but we'll get back to you as soon as we can!
  - type: input
    attributes:
      label: "ridgeplot version"
      description: >
        Which version of ridgeplot are you using?
        You can find out by running `pip show ridgeplot` in your terminal.
      placeholder: "major.minor.patch"
    validations:
      required: true
  - type: input
    attributes:
      label: "Python version"
      description: >
        Which version of Python are you using?
        You can find out by running `python --version` in your terminal.
      placeholder: "major.minor.patch"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Operating system"
      description: Which operating system are you using?
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Description"
      description: "Please describe the issue you encountered."
      placeholder: >
        Please provide a clear and detailed explanation of the issue you experienced, including what you expected to happen instead.

        To help us pinpoint the problem, please include:
        - A minimal, reproducible example that demonstrates the issue.
        - Any error messages, stack traces, or other relevant information.
        - If possible, add a screenshot of the plot generated by ridgeplot on your system. You can easily attach files by dragging and dropping them here.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Are you willing to submit PR?"
      description: >
        This totally optional, but if you’re interested, we’d love to help guide you through the process, especially if you already have a good idea of how to tackle the issue.

        If you'd like to contribute, check the box below and take a look at our [contributing guidelines](https://ridgeplot.readthedocs.io/en/latest/development/contributing.html) for more details.
      options:
        - label: Yes I am willing to submit a PR!
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to report this issue!** 🙏

        We will get back to you as soon as possible.
