name: Setup python

description: Setup python and install dependencies

inputs:
  python-version:
    description: "Python version (e.g. '3.7', '3.8.13', '3.11.0-alpha.1', '3.x')"
    required: true
  requirements-prefix:
    description: "Prefix for requirements file (e.g. 'docs', 'release', 'tests', 'typing', etc.)"
    required: false

outputs:
  sys_platform:
    description: "sys_platform environment marker"
    value: ${{ steps.env_markers.outputs.sys_platform }}
  python_version:
    description: "python_version environment marker"
    value: ${{ steps.env_markers.outputs.python_version }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"
        cache: pip
        cache-dependency-path: "requirements/"

    - name: Ensure pip, setuptools, and wheel are up to date
      shell: bash
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Set environment markers
      id: env_markers
      shell: bash
      run: |
        echo "::set-output name=sys_platform::$(python -c 'import sys; print(sys.platform)')"
        echo "::set-output name=python_version::$(python -c 'import platform; print("".join(platform.python_version_tuple()[:2]))')"

    - name: Install requirements
      if: ${{ inputs.requirements-prefix != '' }}
      shell: bash
      run: |
        python -m pip install -r \
            "requirements/${{ inputs.requirements-prefix }}.${{ steps.env_markers.outputs.python_version }}-${{ steps.env_markers.outputs.sys_platform }}.txt"
