name: Setup python

description: Setup python and install dependencies

inputs:
  python-version:
    description: "Python version (e.g. '3.7', '3.8.13', '3.11.0-alpha.1', '3.x')"
    required: true
  requirements-path:
    description: "Path to requirements.txt file"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"
        cache: pip
        cache-dependency-path: "${{ inputs.requirements-path }}"

    - name: Ensure pip, setuptools, and wheel are up to date
      shell: bash
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install requirements
      if: ${{ inputs.requirements-path != '' }}
      shell: bash
      run: python -m pip install -r "${{ inputs.requirements-path }}"
