# This workflow checks whether the user remembered to update
# the changelog with a relevant entry for the PR.
# This check is skipped if the PR has the "skip news" label.
name: Check Release Notes

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  check:
    name: Check for entry in Changelog
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Default MISSING_CHANGELOG_ENTRY to 1
        run: echo 'MISSING_CHANGELOG_ENTRY=1' >> "$GITHUB_ENV"
      - name: Check changelog if not skipped
        if: "!contains(github.event.pull_request.labels.*.name, 'skip news')"
        run: |
          # shellcheck disable=SC2016
          if grep -p '{gh-pr}`${{ github.event.pull_request.number }}`' ./docs/reference/changelog.md; then
            echo 'MISSING_CHANGELOG_ENTRY=0' >> "$GITHUB_ENV"
          fi

      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Missing changelog entry'

      #                      MISSING_CHANGELOG_ENTRY=1     MISSING_CHANGELOG_ENTRY=0
      # comment-id=''            (A) POST
      # comment-id='1234'        (C) UNRESOLVE                  (B) RESOLVE

      # (A) Post comment

      - name: Post comment
        if: ${{ env.MISSING_CHANGELOG_ENTRY == '1' && steps.fc.outputs.comment-id == '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### :warning: **Missing changelog entry** :warning:

            Please add an entry to the changelog in `docs/reference/changelog.md` for this PR.
            The entry should be in the following format:

            ```markdown
            - Description of the change ({gh-pr}`${{ github.event.pull_request.number }}`)
            ```

            If you don't think a changelog entry is necessary for this change, you can add a `skip news` label to this PR.

      # (D) Resolve comment

      - name: Resolve comment
        if: ${{ env.MISSING_CHANGELOG_ENTRY == '0' && steps.fc.outputs.comment-id != '' }}
        uses: octokit/graphql-action@v2.3.2
        with:
          query: |
            mutation minimizeComment {
              minimizeComment(input: { subjectId: "${{ steps.fc.outputs.comment-id }}", classifier: RESOLVED }) {
                minimizedComment {
                  isMinimized
                  minimizedReason
                }
              }
            }


      # (C) Unresolve comment

      - name: Unresolve comment
        if: ${{ env.MISSING_CHANGELOG_ENTRY == '1' && steps.fc.outputs.comment-id != '' }}
        uses: octokit/graphql-action@v2.3.2
        with:
          query: |
            mutation unminimizeComment {
              unminimizeComment(input: { subjectId: "${{ steps.fc.outputs.comment-id }}" }) {
                unminimizedComment {
                  isMinimized
                }
              }
            }
