name: Greet new users

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            **Thank you for submitting your first issue with us!** 🎉

            Our response time may vary, but we will get back to you as soon as possible.

            To help us help you, please make sure you have provided all the necessary information in your issue's description. 🙏

            If you'd like to contribute to the project (maybe even fix the issue yourself!), please check out our [contributing guidelines](https://ridgeplot.readthedocs.io/en/latest/development/contributing.html).

            Welcome aboard! 🚀
          pr-message: |
            **Thank you for submitting your first pull request with us!** 🎉

            Our response time may vary, but we will get back to you as soon as possible.

            To help us help you, please make sure you have:
            * followed our [contributing guidelines](https://ridgeplot.readthedocs.io/en/latest/development/contributing.html).
            * provided all the necessary information in your pull request's description.
            * all CI check are passing.
            * you have reviewed your own code!

            Welcome aboard! 🚀
