name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install latest pip, setuptools, twine + wheel
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Build wheels
        run: |
          python setup.py sdist bdist_wheel
          twine check --strict dist/*

      - name: Upload to PyPI (test repository)
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_TEST }}
        run: |
          twine upload --repository testpypi --verbose -u '__token__' dist/*

      - name: Upload to PyPI (main repository)
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --verbose -u '__token__' dist/*
