name: Release Workflow

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Set up python project  ---

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Ensure pip, setuptools, and wheel are up to date
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install -e ".[release]"

      # Run Release steps  ---

      # Create GitHub Release

      - name: Generate Changelog for latest release
        run: python scripts/extract_latest_release_notes.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGES-latest.md

      # Publish to PyPi

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel
          twine check --strict dist/*

      - name: Upload to PyPI (test repository)
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_TEST }}
        run: twine upload --repository testpypi --verbose -u '__token__' dist/*

      - name: Upload to PyPI (main repository)
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload --verbose -u '__token__' dist/*
